repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.99.0
    hooks:
      - id: terraform_fmt
        args: ["--recursive"]
      - id: terraform_docs
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_tfupdate
      - id: terraform_wrapper_module_for_each
      - id: terraform_tfsec
        exclude: "^examples/"
        enabled: true
