project_name   = "js-haip"
location       = "canadacentral"
vm_size        = "Standard_D4s_v3"
admin_username = "azureuser"
worker_count   = 1
# arc_cluster_name = "js-haip-arc-cluster"
enable_bastion = true
bastion_sku    = "Basic"
acr_sku        = "Basic"