# Kubernetes Deployment YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-api
  template:
    metadata:
      labels:
        app: ollama-api
    spec:
      imagePullSecrets:
        - name: acr-pull-secret     # ← tell K3s where to get creds
      containers:
      - name: ollama-api
        image: jshaipacr7401.azurecr.io/ollama-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11434
