# Standard Kubernetes Ingress (compatible with K3s Traefik)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-api
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ollama.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ollama-api
            port:
              number: 80
  - http:
      paths:
      - path: /ollama
        pathType: Prefix
        backend:
          service:
            name: ollama-api
            port:
              number: 80
---
# Alternative: Traefik IngressRoute (requires Traefik CRDs to be installed)
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: ollama-api
#   namespace: default
# spec:
#   entryPoints:
#     - web
#   routes:
#   - match: Host(`ollama.local`) || PathPrefix(`/ollama`)
#     kind: Rule
#     services:
#     - name: ollama-api
#       port: 80
