# ClusterIP Service for Ollama API (internal access for Ingress)
# Kubernetes Service YAML
apiVersion: v1
kind: Service
metadata:
  name: ollama-api
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: ollama-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 11434
      # Exposes port 80 for Ingress to route to Ollama API (targetPort 11434)
